# Generated by Django 4.2.2 on 2023-07-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=400)),
                ('logo', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('mount_a', models.FloatField()),
                ('pair_a', models.CharField(max_length=10)),
                ('mount_b', models.FloatField()),
                ('pair_b', models.CharField(max_length=10)),
                ('t_type', models.CharField(choices=[('Compra', 'Buy'), ('Venta', 'Sell')])),
                ('mount_fee', models.FloatField()),
                ('coin_fee', models.CharField(max_length=10)),
                ('pair_b_coin_value', models.FloatField(null=True)),
                ('coin_fee_value', models.FloatField(null=True)),
                ('order_value', models.FloatField(null=True)),
                ('fee_value', models.FloatField(null=True)),
                ('total_value', models.FloatField(null=True)),
                ('comment', models.CharField(max_length=200)),
                ('coin_fee_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coin_Fee_name', to='transactions.coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Exchange_name', to='transactions.exchange')),
                ('pair_a_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pair_A_name', to='transactions.coin')),
                ('pair_b_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pair_B_name', to='transactions.coin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.FloatField()),
                ('pair', models.CharField(max_length=10)),
                ('t_type', models.CharField(choices=[('Compra', 'Buy'), ('Venta', 'Sell'), ('Comision', 'Fee')])),
                ('value', models.FloatField(null=True)),
                ('price_per_coin', models.FloatField(null=True)),
                ('pair_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.coin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
