# Generated by Django 4.2.2 on 2023-07-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='logo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin_fee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pair_a_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pair_b_name',
            field=models.CharField(max_length=100),
        ),
    ]
