# Generated by Django 4.2.2 on 2023-07-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_coin_logo_alter_transaction_coin_fee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin_fee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coin_Fee_name', to='transactions.coin'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Exchange_name', to='transactions.exchange'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pair_a_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pair_A_name', to='transactions.coin'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pair_b_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pair_B_name', to='transactions.coin'),
        ),
    ]
