# Generated by Django 4.2.1 on 2023-07-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_rawtransaction_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransaction',
            name='pair_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coin', to='transactions.coin'),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction', to='transactions.transaction'),
        ),
    ]
