# Generated by Django 4.2.1 on 2023-07-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_rawtransaction_pair_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransaction',
            name='pair_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.coin'),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
