# Generated by Django 4.2.1 on 2023-07-19 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_pair_a_coin_value_delete_rawtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('mount_a', models.FloatField()),
                ('symbol', models.CharField(max_length=10)),
                ('t_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venta'), ('fee', 'Fee')])),
                ('value', models.FloatField(default=0)),
                ('coin_value', models.FloatField(default=0)),
                ('coin_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coin_name', to='transactions.coin')),
            ],
        ),
    ]
