# Generated by Django 4.2.1 on 2023-07-19 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0009_rawtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtransaction',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
